services:
  - type: web
    name: gyn-vision-api
    runtime: docker
    image:
      url: docker.io/sakethkollipara/gyn-vision-api:latest
    plan: starter
    envVars:
      - key: CORS_ORIGINS
        value: https://gynvision.vercel.app
    healthCheckPath: /health
    autoDeploy: false
